apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ntdoc-core.fullname" . }}-config
  labels: {{- include "ntdoc-core.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
