apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ntdoc-core.fullname" . }}-secrets
  labels: {{- include "ntdoc-core.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $k, $v := .Values.secrets }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
