server:
  port: 8070

spring:
  application:
    name: no-tang-doc-core
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none      # none, validate, update, create, create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/ntdoc/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ${KEYCLOAK_CLIENT_ID:}
            authorization-grant-type: authorization_code
            redirect-uri: ${ SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_REDIRECT_URI:}
            scope: openid,profile,email
            client-secret: ${KEYCLOAK_CLIENT_SECRET:} # 修改为你本地KeyClock的Client Secret
        provider:
          keycloak:
            authorization-uri: http://localhost:8080/realms/ntdoc/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/realms/ntdoc/protocol/openid-connect/token
            user-info-uri: http://keycloak:8080/realms/ntdoc/protocol/openid-connect/userinfo
            jwk-set-uri: http://keycloak:8080/realms/ntdoc/protocol/openid-connect/certs
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4.1-mini
          temperature: 0.2

keycloak:
  realm: ntdoc
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:}
  admin:
    realm: master
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  client:
    id: ${KEYCLOAK_CLIENT_ID:}
    secret: ${KEYCLOAK_CLIENT_SECRET:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,beans,loggers
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    # org.hibernate.SQL: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true